"""Writes the fld_* field test plans (Delrich Temple, map 6)."""

OBJ = 0x020B6FD4
ENEMY_SLOTS = range(2, 10)
HDR = "# Field test (generated by a script, emu/gen_fld_plans.py; run with emu/run_fld.sh, see docs/test-report-field.md). Delrich Temple map 6.\n"


def ap(n):
    return ["press A 3", "wait 20"] * n


def pin_enemies(x, y):
    L = []
    for i in ENEMY_SLOTS:
        a = OBJ + i * 0x40 + 4
        L += [f"pin u32 {a:#010x} {x:#x}", f"pin u32 {a + 4:#010x} {y:#x}"]
    return L


PARK = [
    "# park the enemy symbols on a far spawn point (0x138,0x220) so none wanders into Jian"
] + pin_enemies(0x138000, 0x220000)


def free():
    return ["unpin", "include fld_cheats"]


def battle(tag):
    return (
        free()
        + [
            "# low HP and MP so a +30% area-clear refill would show",
            "poke u16 0x020B4668 20",
            "poke u16 0x020B4670 1",
            "poke u32 0x020B6CB4 0x208000",
            "poke u32 0x020B6CB8 0xd4000",
            "# pull the enemy symbols onto Jian for 10 frames: contact starts a battle; win it with A",
        ]
        + pin_enemies(0x208000, 0xD4000)
        + ["wait 10"]
        + free()
        + PARK
        + ap(280)
        + [
            "wait 30",
            f"peek u8 0x020B4912 kills_{tag}",
            f"peek u8 0x020B4913 total_{tag}",
            f"dump 0x020B4658 0x20 jian_{tag}",
            f"dump 0x020B6FD4 0x280 objs_{tag}",
        ]
    )


def chest(tag):
    return [
        "# stand under the blue chest (map object 1 at 0x41C,0xD4), face up, press A",
        "poke u32 0x020B6CB4 0x41c000",
        "poke u32 0x020B6CB8 0xec000",
        "press Up 4",
        "wait 10",
        "press A 3",
        "wait 60",
        f"shot {tag}",
        "press A 3",
        "wait 60",
        "press A 3",
        "wait 60",
        f"dump 0x020B7014 0x40 bluechest_{tag}",
        "peek u32 0x020B0010 fstate_now",
        "poke u32 0x020B6CB4 0x208000",
        "poke u32 0x020B6CB8 0xd4000",
        "wait 10",
    ]


def door(m, tag):
    return (
        free()
        + [
            f"# door to map {m}: field state 0x86 is what a door trigger sets; destination map, entry 400",
            f"poke u16 0x020B77EC {m}",
            "poke u16 0x020B77F0 0x270f",
            "poke u16 0x020B77F2 400",
            "poke u32 0x020B0010 0x86",
            "wait 120",
            f"shot {tag}",
            "peek u16 0x020B6BE4 map_now",
            "dump 0x020B4908 0x18 enemy_table",
            f"dump 0x020B6FD4 0x280 objs_{tag}",
        ]
        + PARK
    )


WATCH = [
    "watch u8 0x020B4912 kills6",
    "watch u8 0x020B4913 total6",
    "watch u16 0x020B490E clock6",
    "watch u16 0x020B6BE4 map",
    "watch u32 0x020B0010 fstate",
    "watch u8 0x020B7848 clear_flag",
    "watch u16 0x020B4668 jian_hp",
    "watch u16 0x020B4670 jian_mp",
    "watch u16 0x020B7034 bluechest_opened",
]


def write(name, lines):
    open(f"emu/plans/{name}.plan", "w").write(HDR + "\n".join(lines) + "\n")


def arrive(vanilla):
    L = [
        "# Part 1: power-on, warp to map 6, win the battle that starts on arrival. Saves state fld_k1.",
        "include boot_from_save",
        "include fld_cheats",
        "include warp6",
    ]
    if vanilla:
        L += ["# original game: Virtue mode so kills count", "poke u8 0x020B4848 1"]
    L += WATCH + ["dump 0x020B6FD4 0x280 objs_arrival"] + ap(260)
    L += ["wait 30"] + PARK + ["wait 30", "peek u8 0x020B4912 kills_b1", "save fld_k1"]
    return L


write("fld_1_arrive", arrive(False))
write("fld_1_arrive_vanilla", arrive(True))
write(
    "fld_2_respawn",
    [
        "# Part 2: second battle, stay on the map, menu, locked blue chest, leave and come back. Saves fld_back.",
        "load fld_k1",
        "include fld_cheats",
    ]
    + PARK
    + ["exec 0x0201D92C load_map", "exec 0x0201E0EC entry_init"]
    + WATCH
    + battle("b2")
    + [
        "# stay on the map: no respawn",
        "wait 1500",
        "peek u8 0x020B4912 kills_wait",
        "dump 0x020B6FD4 0x280 objs_wait",
        "shot f_wait",
        "# open and close the menu",
        "press X 3",
        "wait 90",
        "shot f_menu",
        "press B 3",
        "wait 90",
        "press B 3",
        "wait 90",
        "peek u8 0x020B4912 kills_menu",
        "dump 0x020B6FD4 0x280 objs_menu",
    ]
    + chest("f_chest_locked")
    + door(7, "f_map7")
    + door(6, "f_back6")
    + ["save fld_back"],
)
write(
    "fld_3_round",
    [
        "# Part 3: one battle on map 6 (run until kills == total). Loads and saves fld_round.",
        "load fld_round",
        "include fld_cheats",
    ]
    + PARK
    + WATCH
    + battle("round")
    + ["wait 300", "shot f_round", "save fld_round"],
)
write(
    "fld_4_after_clear",
    [
        "# Part 4: after the clear: blue chest, leave and come back, blue chest again.",
        "load fld_round",
        "include fld_cheats",
    ]
    + PARK
    + WATCH
    + [
        "peek u8 0x020B4912 kills_final",
        "peek u8 0x020B4913 total_final",
        "dump 0x020B4658 0x20 jian_final",
        "shot f_cleared",
    ]
    + chest("f_chest_open")
    + door(7, "f_map7b")
    + door(6, "f_back6b")
    + chest("f_chest_reenter")
    + ["dump 0x020B6FD4 0x280 objs_end"],
)
open("emu/plans/fld_cheats.plan", "w").write(
    "# Strong attack and defence for field tests, HP left alone (test only)\n"
    "pin u8 0x020B4678 255\npin u8 0x020B467C 255\npin u8 0x020B4684 255\npin u8 0x020B468C 255\n"
)
